
<form name="comment" class="form-horizontal" role="form" id="<?php print $this->escape($this->form->getName()) ?>" action="<?php print $this->escape($this->form->getAction()) ?>" method="<?php print $this->escape($this->form->getMethod()) ?>">
  
  <div class="form-group">
    <label class="col-sm-2 control-label"><?php echo $this->form->getElement('name')->getLabel()?></label>
    <div class="col-sm-3 <?php echo $this->form->getElement('name')->hasErrors() ? "has-error": "";?>">
		<input type="text" class="form-control" id="name" name="name" placeholder="" value="<?php echo $this->form->getElement('name')->getValue()?>">
    </div>
  </div>
  <div class="form-group">
    <label for="comment" class="col-sm-2 control-label"><?php echo $this->form->getElement('password')->getLabel()?></label>
    <div class="col-sm-3"<?php echo $this->form->getElement('password')->hasErrors() ? "has-error": "";?>>
      <input type="password" class="form-control" id="password" name="password" placeholder="" value="<?php echo $this->form->getElement('password')->getValue()?>">
    </div>
  </div>
  <div class="form-group">
    <label for="" class="col-sm-2 control-label"></label>
    <div class="col-sm-10">
      <button type="submit" class="btn btn-success">Absenden</button>
    </div>
  </div>
  
</form>

