<div class="row">
    <div class="col-lg-12">
        <ul class="list-group">
            <a href='#' class='list-group-item list-group-item-warning' data-path='<?php echo $this->prevdir; ?>'>..</a>
            <?php foreach ($this->dir as $sDir): ?>
                <?php
                if ($sDir['type'] == 'directory'):
                    $remove = strrchr($sDir['name'], '/');
                    $sUrl = str_replace(" $remove", "", $sDir['name']);
                    ?>
                    <a href='#' class='list-group-item list-group-item-warning' data-path='<?php echo $sUrl; ?>'><?php echo basename($sDir['name']); ?></a>
                <?php endif; ?>
            <?php endforeach; ?>


            <?php foreach ($this->dir as $sDir): ?>
                <?php
                if ($sDir['type'] == 'file'):
                    $remove = strrchr($sDir['name'], '/');
                    $sUrl = str_replace(" $remove", "", $sDir['name']);
                    ?>
                    <span href='#' class='list-group-item' data-path='<?php echo $sUrl; ?>'><?php echo basename($sDir['name']); ?>
                        <div class="tools">
                            <i class="fa fa-plus" data-song="<?php echo $sDir['name'];?>"></i>
                        </div>
                    </span>

                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>