<?php foreach ($this->alben as $album): ?>
    <?php
    $oMeta = $this->lastfm->getAlbuminfo(
            $album->getArtist(), $album->getAlbum()
    );
    $sCover = "";
    foreach ($oMeta->album->image as $image) {
        if ($image->size == 'large') {
            $sCover = $image->{'#text'};
        }
    }
    $sUrl = $this->url(array(
        'controller' => 'index',
        'action' => 'album',
        'alb' => $album->getId())
            , null, TRUE);
    ?>
    <div class="col-md-4">
        <!-- Default box -->
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title"><?php echo $album->getArtist() . " - " . $album->getAlbum(); ?></h3>
            </div>
            <div class="box-body">
                <a href="<?php echo $sUrl; ?>"> 
                    <img data-src="holder.js/140x140" class="img-thumbnail" alt="140x140" src="<?php echo $sCover; ?>" style="width: 140px; height: 140px;">
                </a>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>
<?php endforeach; ?>