
<div class="col-md-4">
        <!-- Default box -->
        <div class="box box-info">
            <div class="box-header">
                <h3 class="box-title"><?php echo $this->album->getArtist() . " - " . $this->album->getAlbum(); ?></h3>
            </div>
            <div class="box-body">
            <table class="table table-condensed table-striped table-bordered">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <th>Titel</th>
                        <th></th>
                    </tr>
                    <?php foreach ($this->songs as $song): ?>
                    <tr>
                        <td><?php echo $song->getId()?></td>
                        <td><?php echo $song->getTitle()?></td>
                        <td><i class="fa fa-plus"></i></td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
            </div>
        </div>
    </div>
</div>
