<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Gruppenübersicht</h3>
            </div><!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tbody><tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Action</th>
                            <th>Find</th>
                            <th>Edit</th>
                        </tr>
                        <?php foreach($this->groups as $group):?>
                        <?php
                        $groupurl = $this->url(array(
                                    'controller' => 'modal',
                                    'action' => 'group',
                                    'id' => $group->getId()
                                ), 'default');
                        ?>
                        <tr>
                            <td><?php echo $group->getId();?></td>
                            <td><?php echo $group->getName();?></td>
                                <td>
                                    <?php if($group->isOn()):?>
                                    <input checked="checked" type="checkbox" name="switch" data-size="small" data-type="group" data-id="<?php echo $group->getId();?>" data-action="toggle" />
                                    <?php else:?>
                                    <input type="checkbox" name="switch" data-size="small" data-type="group" data-id="<?php echo $group->getId();?>" data-action="toggle" />
                                    <?php endif;?>
                                </td>
                            <td><button class="btn btn-info btn-flat setstate" data-type="group" data-id="<?php echo $group->getId();?>" data-action="blink">Info</button></td>
                            
                            <td><a data-toggle="modal" href="<?php echo $groupurl;?>" data-target="#groups">Config</a></td>
                        </tr>
                        <?php endforeach;?>
                    </tbody></table>
            </div><!-- /.box-body -->
        </div><!-- /.box -->
    </div>
</div>