<div class="row">
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    <?php echo count($this->oMpd->getAlbums()); ?>
                </h3>
                <p>
                    Alben
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-ios7-albums"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    <?php echo count($this->oMpd->getArtists()); ?>
                </h3>
                <p>
                    Artists
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-android-friends"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    <?php echo count($this->oMpd->getTitles()); ?>
                </h3>
                <p>
                    Titel
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-music-note"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-9">
        <div class="box box-primary">
            <div class="box-header" data-toggle="tooltip" title="" data-original-title="Header tooltip">
                <h3 class="box-title">Browse</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-primary btn-xs" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-primary btn-xs" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body" id='browsedir'>
            </div><!-- /.box-body -->
        </div>
    </div>
</div>