<div class="row">
    <?php foreach($this->groups as $group):?>
    <div class="col-lg-3 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>
                    <?php echo $group->getName();?>
                </h3>
                <p>
                    <?php echo count($group->getLightIds());?> Lampen
                </p>
            </div>
            <div class="icon">
                <i class="ion ion-ios7-albums"></i>
            </div>
            <a href="#" class="small-box-footer">
                More info <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
    <?php endforeach;?>
</div>

<button class="switch" data-type="group" data-id="1" data-action="toggle">Test</button>