<div class="row">
    <div class="col-lg-7 col-md-9">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <article class="thisbox">
                        <div class="head">
                            <span>Kontakt</span>
                        </div>
                        <div class="body">
                            <div class="row ">
                                <div class="col-lg-12 col-md-12">
                                    <p class="text-muted center-block">
                                        <br />
                                        Vielen Dank für den Besuch auf meiner Website<br />
Du möchtest gerne mehr über meine Shootings erfahren, oder hast andere Fragen?<br /> Dann schick mir eine kurze Nachricht
und du erhälst kurzfristig eine Antwort von mir. 
                                    </p>
                                    <br />
                                    <?php echo $this->partial('forms/kontakt.phtml', array('form' => $this->form));?>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
    </div>
    <?php
    echo $this->render('widgets/profile.phtml');
    ?>
</div>
