<div class="form-box" id="login-box">
    <div class="header">Sign In</div>
    <form action="<?php print $this->escape($this->form->getAction()) ?>" method="<?php print $this->escape($this->form->getMethod()) ?>">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Username">
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Password">
            </div>          
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block btn-flat">Sign me in</button>  
        </div>
    </form>

</div>