<div class="col-md-8">
    <!-- Default box -->
    <div class="box box-solid">
        <div class="box-header">
            <h3 class="box-title"></h3>
            <div class="box-tools pull-right">
                <a href="/index/scan/force/1"><i class="fa fa-refresh"></i> rescan</a>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-condensed table-bordered">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Album</th>
                        <th>Artist</th>
                        <th>Titel</th>
                        <th>Jahr</th>
                        <!--<th>Play</th>-->
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->mp3 as $mp3): ?>
                        <tr>
                            <td><?php echo $mp3->getId() ?></td>
                            <td><?php echo $mp3->getAlbumname() ?></td>
                            <td><?php echo $mp3->getArtist() ?></td>
                            <td><?php echo $mp3->getTitle() ?></td>
                            <td><?php echo $mp3->getYear() ?></td>
                            <!--
                            <td><audio src="<?php echo $mp3->getWebpath() ?>" preload="auto" controls></audio></td>
                            -->
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
