<div class="page-header">
    <h1>myLib <small>- play your songs</small></h1>
</div>

<div class="col-lg-12 col-md-12">
    <div class="row">
        <p>
            <a href="/index/scan/force/1"><span class="glyphicon glyphicon-refresh"> Scan</span></a>
            <br />
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Album</th>
                        <th>Artist</th>
                        <th>Titel</th>
                        <th>Jahr</th>
                        <th>Play</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->mp3 as $mp3): ?>
                    <tr>
                        <td><?php echo $mp3->getId()?></td>
                        <td><?php echo $mp3->getAlbumname()?></td>
                        <td><?php echo $mp3->getArtist()?></td>
                        <td><?php echo $mp3->getTitle()?></td>
                        <td><?php echo $mp3->getYear()?></td>
                        <td><audio src="<?php echo $mp3->getWebpath()?>" preload="auto" controls></audio></td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </p>
    </div>
</div>
