<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Erdis Gallery</title>
</head>
<body>
  <h2>Du hast eine neue Kontaktanfrage von <?php echo $this->form['name'] ?></h2>

 <?php Zend_Debug::dump($this); ?>

</body>
</html>