<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();
$this->headScript()->appendFile($this->baseUrl('/js/site.js'));
?>
<html lang="de">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#ps-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="ps-navbar-collapse">
                <?php
                $options = array('ulClass' => '', 'maxDepth' => 2);
                $mainmenu = $this->navigation()->findOneByClass('nav');
                echo $this->navigation()
                        ->menu()
                        ->renderPartial(
                                $this->navigation()->findOneByClass('nav'), array('navi.phtml', 'default')
                );
                ?>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <?php
        $fm = new Zend_Controller_Action_Helper_FlashMessenger();
        $messages = array_merge($fm->getMessages(), $fm->getCurrentMessages());
        $fm->clearCurrentMessages();
        if (count($messages)) {
            foreach ($messages as $msg) {
                ?>
                <div class='notifications top-right' data-message='<?php echo $msg; ?>'></div>
                <?php
            }
        }
        ?>
    </body>
</html>
