<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
echo $this->doctype();

?>
<html lang="de">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body class="skin-blue">
        <?php echo $this->render('widgets/topnav.phtml');?>
        <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- search form -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <?php
                $options = array('ulClass' => '', 'maxDepth' => 2);
                $mainmenu = $this->navigation()->findOneByClass('nav');
                echo $this->navigation()
                        ->menu()
                        ->renderPartial(
                                $this->navigation()->findOneByClass('nav'), array('navi.phtml', 'default')
                );
                ?>
                </section>
            </aside>
            <!-- Right side column. Contains the navbar and content of the page -->
            <aside class="right-side">
                <section class="content-header">
                    <h1>
                        <?php echo $this->header('head');?>
                        <small><?php echo $this->header('foot');?></small>
                    </h1>
                    <?php
                    echo $this->navigation()
                            ->breadcrumbs()
                            ->renderPartial(
                                    $this->navigation()->findOneByClass('nav'), array('breadcrumb.phtml', 'default')
                                    );
                    ?>
                </section>
                <!-- Main content -->
                <section class="content">
                    <?php
                    echo $this->layout()->content;
                    ?>
                </section>
            </aside>
        </div>
        <?php
        $fm = new Zend_Controller_Action_Helper_FlashMessenger();
        $messages = array_merge($fm->getMessages(), $fm->getCurrentMessages());
        $fm->clearCurrentMessages();
        if (count($messages)) {
            foreach ($messages as $msg) {
                ?>
                <div class='notifications top-right' data-message='<?php echo $msg; ?>'></div>
                <?php
            }
        }
        ?>
    </body>
</html>
