<?php

$acl = Zend_Registry::get("acl");

$html[] = "<ul class='sidebar-menu'>";

foreach ($this->container as $page) {
    if (!$this->navigation()->accept($page)) {
        continue;
    }
    $active = "";
    foreach($page->pages as $sub) {
        if($sub->isActive()) {
            $active = " active";
        }
    }
    
    if ($page->pages) {
        $page->setClass("dropdown-toggle");
        $html[] = "<li class='treeview$active'>";
    } else {
        $html[] = "<li>";
    }
    if ($page->getController()) {
        $html[] = $this->menu()->htmlify($page) . PHP_EOL;
    } else {
        $html[] = "<a href='#'>";
        $html[] = "<i class='fa fa-bar-chart-o'></i>";
        $html[] = sprintf("<span>%s</span>", $this->translate($page->getLabel()));
        $html[] = "<i class='fa fa-angle-left pull-right'></i>";
        $html[] = "</a>";
    }

    if (!empty($page->pages) && $this->navigation()->accept($page)) {
        $html[] = "<ul class='treeview-menu'>";
        foreach ($page->pages as $subpage) {
            $active = "";
            if ($subpage->isActive()) {
                $active = "active";
            }
            if (!$this->navigation()->accept($subpage)) {
                continue;
            }
            
            $html[] = "<li class='$active'>";
            $html[] = sprintf("<a href='%s'>", $subpage->getHref());
            $html[] = "<i class='fa fa-angle-double-right'></i>";
            $html[] = $this->translate($subpage->getLabel());
            $html[] = "</a>";
            $html[] = "</li>";
        }
        $html[] = "</ul>";
    }
    $html[] = "</li>";
}
$html[] = "</ul>";

echo join(PHP_EOL, $html);
