<div class="row">
    <div class="col-lg-9 col-md-9">
            <div class="row">
                <div class="col-lg-9 col-md-9">
                    <article class="thisbox">
                        <div class="head">
                            <span>Es ist ein Fehler aufgetreten</span>
                        </div>
                        <div class="body">
                            <div class="row">
                                <div class="col-lg-9 col-md-9">
                                    <p class="text-muted">
                                        So wie Einhörner existiert auch diese Seite nicht...oder zumindest nicht mehr!
                                        Aber so wie sie, ist es Magie und die kann dich hintragen wohin du willst!
                                    </p>
                                    <p>
                                    <img class="center-block img-thumbnail img-responsive" src="/img/404.jpg" />
                                    </p>
                                </div>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
    </div>
</div>