<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Erdis Gallery</title>
</head>
<body>
  <h2>Du hast eine neue Kontaktanfrage</h2>
  <h3>Absender:</h3>
  <p>
      <?php echo $this->form['name']; ?>
  </p>
  <h3>Mail:</h3>
  <p>
      <?php echo $this->form['mail']; ?>
  </p>
  <h3>Nachricht:</h3>
  <p>
      <?php echo $this->form['comment']; ?>
  </p>
</body>
</html>